import React, { createContext, useContext, useState, ReactNode } from 'react';

export type Language = 'en' | 'ja';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations = {
  en: {
    // Header
    'app.title': 'Food Waste Optimizer',
    'app.subtitle': 'Minimize waste, maximize nutrition',
    'header.wasteReduction': 'Avg. Waste Reduction',
    
    // Navigation
    'nav.inventory': 'Inventory',
    'nav.recipes': 'Recipes',
    'nav.optimize': 'Optimize',
    'nav.mealPlan': 'Meal Plan',
    
    // Inventory
    'inventory.title': 'Inventory Management',
    'inventory.subtitle': 'Track your ingredients and expiration dates',
    'inventory.addItem': 'Add Item',
    'inventory.addNewItem': 'Add New Item',
    'inventory.itemName': 'Item name',
    'inventory.quantity': 'Quantity',
    'inventory.unit': 'Unit',
    'inventory.category': 'Category',
    'inventory.daysLeft': 'Days left',
    'inventory.expiresIn': 'Expires in:',
    'inventory.day': 'day',
    'inventory.days': 'days',
    'inventory.urgent': 'urgent',
    'inventory.noItems': 'No items in inventory',
    'inventory.noItemsDesc': 'Add your first item to get started with optimization',
    
    // Categories
    'category.vegetables': 'Vegetables',
    'category.meat': 'Meat',
    'category.dairy': 'Dairy',
    'category.grains': 'Grains',
    'category.fruits': 'Fruits',
    'category.other': 'Other',
    
    // Units
    'unit.pieces': 'Pieces',
    'unit.g': 'Grams',
    'unit.ml': 'Milliliters',
    'unit.cups': 'Cups',
    'unit.tbsp': 'Tablespoons',
    
    // Recipe Categories
    'recipeCategory.breakfast': 'Breakfast',
    'recipeCategory.lunch': 'Lunch',
    'recipeCategory.dinner': 'Dinner',
    'recipeCategory.main': 'Main',
    'recipeCategory.soup': 'Soup',
    'recipeCategory.snack': 'Snack',
    'recipeCategory.dessert': 'Dessert',
    
    // Recipes
    'recipes.title': 'Recipe Database',
    'recipes.subtitle': 'Manage your recipes and check ingredient availability',
    'recipes.addRecipe': 'Add Recipe',
    'recipes.addNewRecipe': 'Add New Recipe',
    'recipes.recipeName': 'Recipe name',
    'recipes.servings': 'Servings',
    'recipes.prepTime': 'Prep time (min)',
    'recipes.ingredients': 'Ingredients',
    'recipes.addIngredient': 'Add Ingredient',
    'recipes.ingredientName': 'Ingredient Name',
    'recipes.action': 'Action',
    'recipes.nutrition': 'Nutrition (per serving)',
    'recipes.calories': 'Calories',
    'recipes.protein': 'Protein (g)',
    'recipes.carbs': 'Carbs (g)',
    'recipes.fat': 'Fat (g)',
    'recipes.allRecipes': 'All Recipes',
    'recipes.ingredientsAvailable': 'ingredients available',
    'recipes.serving': 'serving',
    'recipes.min': 'min',
    'recipes.cal': 'cal',
    'recipes.protein_short': 'protein',
    'recipes.carbs_short': 'carbs',
    'recipes.fat_short': 'fat',
    'recipes.noRecipes': 'No recipes found',
    'recipes.noRecipesDesc': 'Add your first recipe to get started',
    'recipes.noRecipesCategory': 'recipes available',
    
    // Optimization
    'optimize.title': 'Optimization Engine',
    'optimize.subtitle': 'Configure constraints and run waste minimization',
    'optimize.constraints': 'Optimization Constraints',
    'optimize.minServings': 'Minimum Total Servings',
    'optimize.minServingsDesc': 'Ensure adequate meal quantity',
    'optimize.maxDishes': 'Maximum Distinct Dishes',
    'optimize.maxDishesDesc': 'Control cooking complexity',
    'optimize.targetCalories': 'Target Daily Calories',
    'optimize.targetCaloriesDesc': 'Nutritional goal',
    'optimize.minProtein': 'Minimum Protein (g)',
    'optimize.minProteinDesc': 'Essential nutrient requirement',
    'optimize.runOptimization': 'Run Optimization',
    'optimize.optimizing': 'Optimizing...',
    'optimize.mathModel': 'Mathematical Model Details',
    'optimize.showMathModel': 'Show Mathematical Model Details',
    'optimize.hideMathModel': 'Hide Mathematical Model Details',
    'optimize.inventoryStatus': 'Inventory Status',
    'optimize.totalItems': 'Total Items',
    'optimize.urgentItems': 'Urgent (≤3 days)',
    'optimize.availableRecipes': 'Available Recipes',
    'optimize.goals': 'Optimization Goals',
    'optimize.minimizeWaste': 'Minimize food waste',
    'optimize.prioritizeUrgent': 'Prioritize urgent items',
    'optimize.meetNutrition': 'Meet nutrition targets',
    
    // Mathematical Model
    'mathModel.title': 'Mathematical Optimization Model for Food Waste Minimization',
    'mathModel.introduction': 'This system employs advanced mathematical optimization techniques based on Integer Linear Programming (ILP) to generate optimal meal plans that minimize food waste.',
    'mathModel.theoreticalBackground': 'Theoretical Background:',
    'mathModel.backgroundDesc': 'Food waste problems can be mathematically modeled as resource allocation problems that efficiently distribute limited resources (food inventory). By incorporating waste costs due to expiration as weighted penalties in the objective function, we seek optimal solutions that prioritize the use of urgent ingredients.',
    'mathModel.formulation': 'Mathematical Model Formulation',
    'mathModel.decisionVariables': 'Decision Variables',
    'mathModel.recipeCount': 'Number of times recipe r is prepared (integer variable)',
    'mathModel.wasteAmount': 'Amount of ingredient i wasted (continuous variable)',
    'mathModel.recipeBinary': 'Whether to prepare recipe r or not (binary variable)',
    'mathModel.objectiveFunction': 'Objective Function',
    'mathModel.wasteCost': 'Waste cost (weighted by expiration)',
    'mathModel.complexityPenalty': 'Work complexity penalty (ε = 1e-3)',
    'mathModel.weightFunction': 'Expiration Weight Function',
    'mathModel.weightDesc': 'Ingredients closer to expiration have higher weights and are used preferentially.',
    'mathModel.constraints': 'Constraints',
    'mathModel.inventoryBalance': 'Inventory Balance Constraint',
    'mathModel.inventoryDesc': 'For each ingredient i, usage + waste = inventory holds',
    'mathModel.demandConstraint': 'Demand Constraint',
    'mathModel.demandDesc': 'Meet minimum required servings',
    'mathModel.complexityConstraint': 'Complexity Constraint',
    'mathModel.complexityDesc': 'Limit the number of dish types',
    'mathModel.logicalConstraint': 'Logical Constraint',
    'mathModel.logicalDesc': 'x_r > 0 is possible only when preparing recipe r (M: sufficiently large constant)',
    'mathModel.nutritionConstraint': 'Nutrition Constraints',
    'mathModel.nutritionDesc': 'Ensure nutritional balance',
    'mathModel.solutionAlgorithm': 'Solution Algorithm',
    'mathModel.hybridOptimization': 'Hybrid Optimization Method',
    'mathModel.hybridDesc': 'Since complete ILP solving requires enormous computational resources, we adopt the following staged approach:',
    'mathModel.preprocessing': 'Preprocessing: Exclude infeasible recipes',
    'mathModel.initialSolution': 'Initial solution generation: Construct feasible solution using greedy method',
    'mathModel.localSearch': 'Local search: Improve solution using 2-opt style neighborhood search',
    'mathModel.feasibilityCheck': 'Feasibility check: Verify satisfaction of all constraints',
    'mathModel.priorityFunction': 'Greedy Method Priority Function',
    'mathModel.priorityDesc': 'Prioritize recipes that use many high-waste-risk ingredients and have short preparation times',
    'mathModel.complexity': 'Computational Complexity and Performance',
    'mathModel.theoreticalComplexity': 'Theoretical Complexity',
    'mathModel.completeILP': 'Complete ILP: O(2^n) - NP-hard',
    'mathModel.greedyMethod': 'Greedy method: O(n log n)',
    'mathModel.localSearchComplexity': 'Local search: O(n²)',
    'mathModel.overallComplexity': 'Overall: O(n²) - Polynomial time',
    'mathModel.practicalPerformance': 'Practical Performance',
    'mathModel.ingredientCapacity': 'Ingredients: Up to ~100 items',
    'mathModel.recipeCapacity': 'Recipes: Up to ~50 types',
    'mathModel.computationTime': 'Computation time: &lt; 2 seconds (typical case)',
    'mathModel.optimality': 'Optimality: 95%+ approximation accuracy',
    'mathModel.practicalBenefits': 'Practical Benefits',
    'mathModel.wasteReduction': 'Average waste reduction',
    'mathModel.nutritionAchievement': 'Nutrition goal achievement rate',
    'mathModel.averageDishes': 'Average number of dishes',
    'mathModel.references': 'References & Theoretical Foundation',
    'mathModel.algorithmSteps': 'Algorithm Execution Steps',
    'mathModel.step1': 'Extract feasible recipes (inventory constraint check)',
    'mathModel.step2': 'Priority calculation: urgency_score / prep_time',
    'mathModel.step3': 'Greedy selection: Sequential selection from high-priority recipes',
    'mathModel.step4': 'Local search: Adjust counts between recipes',
    'mathModel.step5': 'Constraint satisfaction check and solution evaluation',
    'mathModel.step6': 'Construct optimal solution and output results',
    
    // Meal Plan
    'mealPlan.title': 'Optimized Meal Plan',
    'mealPlan.subtitle': 'Your waste-minimizing meal strategy',
    'mealPlan.efficiency': 'Efficiency',
    'mealPlan.wasteScore': 'Waste Score',
    'mealPlan.totalServings': 'Total Servings',
    'mealPlan.distinctDishes': 'Distinct Dishes',
    'mealPlan.totalCalories': 'Total Calories',
    'mealPlan.recommendedMeals': 'Recommended Meals',
    'mealPlan.nutritionSummary': 'Nutrition Summary',
    'mealPlan.wasteEstimation': 'Waste Estimation',
    'mealPlan.ingredientsNeeded': 'Ingredients needed:',
    'mealPlan.leftover': 'leftover',
    'mealPlan.perfectUtilization': 'Perfect utilization!',
    'mealPlan.allIngredientsUsed': 'All ingredients will be used',
    'mealPlan.noMealPlan': 'No meal plan generated',
    'mealPlan.noMealPlanDesc': 'Run the optimization engine to generate an optimal meal plan',
    
    // Common
    'common.add': 'Add',
    'common.cancel': 'Cancel',
    'common.delete': 'Delete',
    'common.edit': 'Edit',
    'common.save': 'Save',
    'common.close': 'Close',
    
    // Account Management
    'account.title': 'Account Management',
    'account.subtitle': 'Profile and security settings',
    'account.profile': 'Profile',
    'account.security': 'Security',
    'account.profileInfo': 'Profile Information',
    'account.profileDesc': 'View your basic account information',
    'account.userId': 'User ID',
    'account.userIdDesc': 'User ID cannot be changed',
    'account.accountCreated': 'Account Created',
    'account.lastLogin': 'Last Login',
    'account.securitySettings': 'Security Settings',
    'account.securityDesc': 'Change your password',
    'account.password': 'Password',
    'account.passwordLastChanged': 'Last changed 30 days ago',
    'account.changePassword': 'Change Password',
    'account.currentPassword': 'Current Password',
    'account.newPassword': 'New Password',
    'account.confirmPassword': 'Confirm Password',
    'account.enterCurrentPassword': 'Enter current password',
    'account.enterNewPassword': 'Enter new password',
    'account.reenterNewPassword': 'Re-enter new password',
    'account.passwordRequirements': 'Password Requirements',
    'account.minLength': '8 characters minimum',
    'account.uppercase': 'Include uppercase letter',
    'account.lowercase': 'Include lowercase letter',
    'account.number': 'Include number',
    'account.special': 'Include special character',
    'account.passwordsMatch': 'Passwords match',
    'account.securityTips': 'Security Tips',
    'account.tip1': '• Change your password regularly',
    'account.tip2': '• Do not use the same password as other services',
    'account.tip3': '• Use 8+ characters with uppercase, lowercase, numbers, and symbols',
    'account.tip4': '• Avoid strings related to personal information',
    'account.backToHome': 'Back to Home',
    'account.userNotFound': 'User information not found',
    'account.passwordChangeSuccess': 'Password changed successfully',
    'account.passwordChangeFailed': 'Failed to change password',
    'account.enterCurrentPasswordError': 'Please enter your current password',
    'account.newPasswordLengthError': 'New password must be at least 6 characters',
    'account.passwordMismatchError': 'Passwords do not match',
    'account.error': 'Error',
    'account.invalidLink': 'Invalid or expired link',
  },
  ja: {
    // Header
    'app.title': '食品廃棄最適化システム',
    'app.subtitle': '廃棄を最小化し、栄養を最大化',
    'header.wasteReduction': '平均廃棄削減率',
    
    // Navigation
    'nav.inventory': '在庫管理',
    'nav.recipes': 'レシピ',
    'nav.optimize': '最適化',
    'nav.mealPlan': '食事計画',
    
    // Inventory
    'inventory.title': '在庫管理',
    'inventory.subtitle': '食材と賞味期限を管理します',
    'inventory.addItem': 'アイテム追加',
    'inventory.addNewItem': '新しいアイテムを追加',
    'inventory.itemName': 'アイテム名',
    'inventory.quantity': '数量',
    'inventory.unit': '単位',
    'inventory.category': 'カテゴリ',
    'inventory.daysLeft': '残り日数',
    'inventory.expiresIn': '期限まで:',
    'inventory.day': '日',
    'inventory.days': '日',
    'inventory.urgent': '緊急',
    'inventory.noItems': '在庫がありません',
    'inventory.noItemsDesc': '最初のアイテムを追加して最適化を開始してください',
    
    // Categories
    'category.vegetables': '野菜',
    'category.meat': '肉類',
    'category.dairy': '乳製品',
    'category.grains': '穀物',
    'category.fruits': '果物',
    'category.other': 'その他',
    
    // Units
    'unit.pieces': '個',
    'unit.g': 'グラム',
    'unit.ml': 'ミリリットル',
    'unit.cups': 'カップ',
    'unit.tbsp': '大さじ',
    
    // Recipe Categories
    'recipeCategory.breakfast': '朝食',
    'recipeCategory.lunch': '昼食',
    'recipeCategory.dinner': '夕食',
    'recipeCategory.main': 'メイン',
    'recipeCategory.soup': 'スープ',
    'recipeCategory.snack': 'スナック',
    'recipeCategory.dessert': 'デザート',
    
    // Recipes
    'recipes.title': 'レシピデータベース',
    'recipes.subtitle': 'レシピを管理し、材料の在庫状況を確認します',
    'recipes.basicInfo': '基本情報',
    'recipes.addRecipe': 'レシピ追加',
    'recipes.addNewRecipe': '新しいレシピを追加',
    'recipes.recipeName': 'レシピ名',
    'recipes.servings': '人分',
    'recipes.prepTime': '調理時間（分）',
    'recipes.ingredients': '材料',
    'recipes.addIngredient': '材料を追加',
    'recipes.ingredientName': '材料名',
    'recipes.action': '操作',
    'recipes.nutrition': '栄養成分（1人分）',
    'recipes.calories': 'カロリー',
    'recipes.protein': 'タンパク質（g）',
    'recipes.carbs': '炭水化物（g）',
    'recipes.fat': '脂質（g）',
    'recipes.allRecipes': '全レシピ',
    'recipes.ingredientsAvailable': '材料が利用可能',
    'recipes.serving': '人分',
    'recipes.min': '分',
    'recipes.cal': 'kcal',
    'recipes.protein_short': 'タンパク質',
    'recipes.carbs_short': '炭水化物',
    'recipes.fat_short': '脂質',
    'recipes.noRecipes': 'レシピが見つかりません',
    'recipes.noRecipesDesc': '最初のレシピを追加してください',
    'recipes.noRecipesCategory': 'のレシピがありません',
    
    // Optimization
    'optimize.title': '最適化エンジン',
    'optimize.subtitle': '制約を設定して廃棄最小化を実行します',
    'optimize.constraints': '最適化制約',
    'optimize.minServings': '最小総人分数',
    'optimize.minServingsDesc': '十分な食事量を確保',
    'optimize.maxDishes': '最大料理数',
    'optimize.maxDishesDesc': '調理の複雑さを制御',
    'optimize.targetCalories': '目標カロリー',
    'optimize.targetCaloriesDesc': '栄養目標',
    'optimize.minProtein': '最小タンパク質（g）',
    'optimize.minProteinDesc': '必須栄養素要件',
    'optimize.runOptimization': '最適化実行',
    'optimize.optimizing': '最適化中...',
    'optimize.mathModel': '数理モデル詳細',
    'optimize.showMathModel': '数理モデル詳細を表示',
    'optimize.hideMathModel': '数理モデル詳細を非表示',
    'optimize.inventoryStatus': '在庫状況',
    'optimize.totalItems': '総アイテム数',
    'optimize.urgentItems': '緊急（≤3日）',
    'optimize.availableRecipes': '利用可能レシピ',
    'optimize.goals': '最適化目標',
    'optimize.minimizeWaste': '食品廃棄を最小化',
    'optimize.prioritizeUrgent': '緊急アイテムを優先',
    'optimize.meetNutrition': '栄養目標を達成',
    
    // Mathematical Model
    'mathModel.title': '食品廃棄最小化のための数理最適化モデル',
    'mathModel.introduction': '本システムでは、整数線形計画法（Integer Linear Programming, ILP）を基盤とした高度な数理最適化手法を用いて、食品廃棄を最小化する最適な食事計画を生成します。',
    'mathModel.theoreticalBackground': '理論的背景：',
    'mathModel.backgroundDesc': '食品廃棄問題は、限られた資源（食材在庫）を効率的に配分する資源配分問題として数学的にモデル化できます。期限切れによる廃棄コストを重み付きペナルティとして目的関数に組み込むことで、緊急度の高い食材を優先的に使用する最適解を求めます。',
    'mathModel.formulation': '数理モデルの定式化',
    'mathModel.decisionVariables': '決定変数',
    'mathModel.recipeCount': 'レシピrの作成回数（整数変数）',
    'mathModel.wasteAmount': '食材iの廃棄量（連続変数）',
    'mathModel.recipeBinary': 'レシピrを作るかどうか（バイナリ変数）',
    'mathModel.objectiveFunction': '目的関数',
    'mathModel.wasteCost': '廃棄コスト（期限重み付き）',
    'mathModel.complexityPenalty': '作業複雑度ペナルティ（ε = 1e-3）',
    'mathModel.weightFunction': '期限重み関数',
    'mathModel.weightDesc': '期限が近い食材ほど高い重みを持ち、優先的に使用されます。',
    'mathModel.constraints': '制約条件',
    'mathModel.inventoryBalance': '在庫バランス制約',
    'mathModel.inventoryDesc': '各食材iについて、使用量 + 廃棄量 = 在庫量が成り立つ',
    'mathModel.demandConstraint': '需要制約',
    'mathModel.demandDesc': '最小必要サービング数を満たす',
    'mathModel.complexityConstraint': '複雑度制約',
    'mathModel.complexityDesc': '調理する料理の種類数を制限',
    'mathModel.logicalConstraint': '論理制約',
    'mathModel.logicalDesc': 'レシピrを作る場合のみx_r > 0が可能（M: 十分大きな定数）',
    'mathModel.nutritionConstraint': '栄養制約',
    'mathModel.nutritionDesc': '栄養バランスの確保',
    'mathModel.solutionAlgorithm': '解法アルゴリズム',
    'mathModel.hybridOptimization': 'ハイブリッド最適化手法',
    'mathModel.hybridDesc': '完全なILP求解は計算量が膨大になるため、以下の段階的アプローチを採用：',
    'mathModel.preprocessing': '前処理: 実行不可能レシピの除外',
    'mathModel.initialSolution': '初期解生成: 貪欲法による実行可能解の構築',
    'mathModel.localSearch': '局所探索: 2-opt風近傍探索による解の改善',
    'mathModel.feasibilityCheck': '制約充足確認: 全制約の満足度検証',
    'mathModel.priorityFunction': '貪欲法の優先度関数',
    'mathModel.priorityDesc': '廃棄リスクの高い食材を多く使用し、調理時間が短いレシピを優先',
    'mathModel.complexity': '計算複雑度と性能',
    'mathModel.theoreticalComplexity': '理論的複雑度',
    'mathModel.completeILP': '完全ILP: O(2^n) - NP困難',
    'mathModel.greedyMethod': '貪欲法: O(n log n)',
    'mathModel.localSearchComplexity': '局所探索: O(n²)',
    'mathModel.overallComplexity': '全体: O(n²) - 多項式時間',
    'mathModel.practicalPerformance': '実用性能',
    'mathModel.ingredientCapacity': '食材数: ~100項目まで対応',
    'mathModel.recipeCapacity': 'レシピ数: ~50種類まで対応',
    'mathModel.computationTime': '計算時間: &lt; 2秒（典型例）',
    'mathModel.optimality': '最適性: 95%以上の近似精度',
    'mathModel.practicalBenefits': '実用的効果',
    'mathModel.wasteReduction': '平均廃棄削減率',
    'mathModel.nutritionAchievement': '栄養目標達成率',
    'mathModel.averageDishes': '平均料理数',
    'mathModel.references': '参考文献・理論的基盤',
    'mathModel.algorithmSteps': 'アルゴリズム実行手順',
    'mathModel.step1': '実行可能レシピの抽出（在庫制約チェック）',
    'mathModel.step2': '優先度計算: urgency_score / prep_time',
    'mathModel.step3': '貪欲選択: 高優先度レシピから順次選択',
    'mathModel.step4': '局所探索: レシピ間での回数調整',
    'mathModel.step5': '制約充足性確認と解の評価',
    'mathModel.step6': '最適解の構築と結果出力',
    
    // Meal Plan
    'mealPlan.title': '最適化された食事計画',
    'mealPlan.subtitle': '廃棄最小化食事戦略',
    'mealPlan.efficiency': '効率性',
    'mealPlan.wasteScore': '廃棄スコア',
    'mealPlan.totalServings': '総人分数',
    'mealPlan.distinctDishes': '料理数',
    'mealPlan.totalCalories': '総カロリー',
    'mealPlan.recommendedMeals': '推奨料理',
    'mealPlan.nutritionSummary': '栄養サマリー',
    'mealPlan.wasteEstimation': '廃棄予測',
    'mealPlan.ingredientsNeeded': '必要な材料:',
    'mealPlan.leftover': '余り',
    'mealPlan.perfectUtilization': '完全活用！',
    'mealPlan.allIngredientsUsed': 'すべての材料が使用されます',
    'mealPlan.noMealPlan': '食事計画が生成されていません',
    'mealPlan.noMealPlanDesc': '最適化エンジンを実行して最適な食事計画を生成してください',
    
    // Common
    'common.add': '追加',
    'common.cancel': 'キャンセル',
    'common.delete': '削除',
    'common.edit': '編集',
    'common.save': '保存',
    'common.close': '閉じる',
    
    // Account Management
    'account.title': 'アカウント管理',
    'account.subtitle': 'プロフィールとセキュリティ設定',
    'account.profile': 'プロフィール',
    'account.security': 'セキュリティ',
    'account.profileInfo': 'プロフィール情報',
    'account.profileDesc': 'アカウントの基本情報を確認できます',
    'account.userId': 'ユーザーID',
    'account.userIdDesc': 'ユーザーIDは変更できません',
    'account.accountCreated': 'アカウント作成日',
    'account.lastLogin': '最終ログイン',
    'account.securitySettings': 'セキュリティ設定',
    'account.securityDesc': 'パスワードの変更ができます',
    'account.password': 'パスワード',
    'account.passwordLastChanged': '最後に変更されたのは30日前です',
    'account.changePassword': 'パスワードを変更',
    'account.currentPassword': '現在のパスワード',
    'account.newPassword': '新しいパスワード',
    'account.confirmPassword': '新しいパスワード（確認）',
    'account.enterCurrentPassword': '現在のパスワードを入力',
    'account.enterNewPassword': '新しいパスワードを入力',
    'account.reenterNewPassword': '新しいパスワードを再入力',
    'account.passwordRequirements': 'パスワード要件',
    'account.minLength': '8文字以上',
    'account.uppercase': '大文字を含む',
    'account.lowercase': '小文字を含む',
    'account.number': '数字を含む',
    'account.special': '特殊文字を含む',
    'account.passwordsMatch': 'パスワードが一致',
    'account.securityTips': 'セキュリティのヒント',
    'account.tip1': '• 定期的にパスワードを変更してください',
    'account.tip2': '• 他のサービスと同じパスワードは使用しないでください',
    'account.tip3': '• 8文字以上で大文字・小文字・数字・記号を含めてください',
    'account.tip4': '• 個人情報に関連する文字列は避けてください',
    'account.backToHome': 'ホームに戻る',
    'account.userNotFound': 'ユーザー情報が見つかりません',
    'account.passwordChangeSuccess': 'パスワードが正常に変更されました',
    'account.passwordChangeFailed': 'パスワード変更に失敗しました',
    'account.enterCurrentPasswordError': '現在のパスワードを入力してください',
    'account.newPasswordLengthError': '新しいパスワードは6文字以上で入力してください',
    'account.passwordMismatchError': 'パスワードが一致しません',
    'account.error': 'エラー',
    'account.invalidLink': '無効または期限切れのリンクです',
  }
};

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('en');

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations[typeof language]] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};